// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snail.Permission.Test;

namespace Snail.Permission.Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20190921113348_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Snail.Permission.Test.TestOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("CreaterId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<Guid>("ParentId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<Guid>("UpdaterId");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Snail.Permission.Test.TestPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("CreaterId");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("ResourceId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<Guid>("UpdaterId");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Snail.Permission.Test.TestResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("CreaterId");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Key");

                    b.Property<int>("ParentId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<Guid>("UpdaterId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Snail.Permission.Test.TestRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("CreaterId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("RoleName");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<Guid>("UpdaterId");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Snail.Permission.Test.TestUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("CreaterId");

                    b.Property<string>("Email");

                    b.Property<Guid>("Gender");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LoginName");

                    b.Property<string>("Phone");

                    b.Property<string>("Pwd");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<Guid>("UpdaterId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Snail.Permission.Test.TestUserOrg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("CreaterId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OrgId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<Guid>("UpdaterId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserOrgs");
                });

            modelBuilder.Entity("Snail.Permission.Test.TestUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("CreaterId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("RoleId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<Guid>("UpdaterId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
