// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snail.Permission.Test;

namespace Snail.Permission.Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Snail.Permission.Entity.Org", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creater");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("ParentId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("Updater");

                    b.HasKey("Id");

                    b.ToTable("Orgs");
                });

            modelBuilder.Entity("Snail.Permission.Entity.Resource", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creater");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("ParentId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("Updater");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Snail.Permission.Entity.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creater");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("Updater");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Snail.Permission.Entity.RoleResource", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creater");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ResourceId");

                    b.Property<string>("RoleId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("Updater");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Snail.Permission.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creater");

                    b.Property<string>("Email");

                    b.Property<int>("Gender");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Pwd");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("Updater");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Snail.Permission.Entity.UserOrg", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creater");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("OrgId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("Updater");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserOrgs");
                });

            modelBuilder.Entity("Snail.Permission.Entity.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Creater");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("RoleId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("Updater");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
